apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "llm-gateway.name" . }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "llm-gateway.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
