{{- if and (not .Values.secret.existingSecret) .Values.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llm-gateway.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
{{- with .Values.secret.data }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
