CREATE TABLE IF NOT EXISTS backends (
  id                              INTEGER PRIMARY KEY AUTOINCREMENT,
  name                            TEXT NOT NULL,
  protocol                        TEXT NOT NULL DEFAULT 'h1' CHECK(protocol IN ('h1', 'h2c', 'h2')),
  base_url                        TEXT NOT NULL,
  enabled                         INTEGER NOT NULL DEFAULT 1,
  models_served                   TEXT NOT NULL DEFAULT '[]',
  weight                          INTEGER NOT NULL DEFAULT 0,
  max_concurrent                  INTEGER NOT NULL DEFAULT 0,
  kv_cache_aware_routing          INTEGER NOT NULL DEFAULT 0,
  metrics_url                     TEXT,
  scrape_interval                 INTEGER NOT NULL DEFAULT 30,
  max_idle_connections_per_host   INTEGER NOT NULL DEFAULT 1,
  idle_connection_timeout         TEXT NOT NULL DEFAULT '30000000000',
  dial_timeout                    TEXT NOT NULL DEFAULT '30000000000',
  stream_stall_timeout            TEXT NOT NULL DEFAULT '60000000000',
  response_header_timeout         TEXT NOT NULL DEFAULT '30000000000',
  failure_threshold               INTEGER NOT NULL DEFAULT 3,
  rolling_window                  INTEGER NOT NULL DEFAULT 60,
  open_base                       INTEGER NOT NULL DEFAULT 2,
  open_max                        INTEGER NOT NULL DEFAULT 10,
  backoff_factor                  INTEGER NOT NULL DEFAULT 2,
  half_open_probes                INTEGER NOT NULL DEFAULT 1,
  half_open_successes             INTEGER NOT NULL DEFAULT 2,
  health_check_path               TEXT NOT NULL DEFAULT '/health',
  health_interval                 TEXT NOT NULL DEFAULT '30000000000',
  verify_tls_cert                 INTEGER NOT NULL DEFAULT 1,
  description                     TEXT,
  labels                          TEXT NOT NULL DEFAULT '[]',
  created_at                      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
  updated_at                      TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
